### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by darnoldi** [appwrite/sdk-for-dotnet#18]
### 💭 Description

The readme states that to install the package in your projects, issue the command `Install-Package Appwrite -Version 0.3.0`.

This returns the error `Install-Package : NU1102: Unable to find package Appwrite with version (>= 0.3.0)`

It appears that the nuget repo only has up to version 0.2.0. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by eldadfux** [comment]
This repo is still a work in progress, and we'll officially be announced once we add support for structured response types.
