### ISSUE TITLE
🚀 Feature: Support GA Release

### ISSUE THREAD

**Issue by PaulSorauer-IPG** [appwrite/sdk-for-dotnet#19]
### 🔖 Feature description

Any plans to officially support the Appwrite server version 1.x, now that it's gone to GA?

### 🎤 Pitch

Would be nice to support the latest, full release. (Please). :D

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
We want to add proper response model support before going 1.x with the SDK.

**Comment by AathifMahir** [comment]
> We want to add proper response model support before going 1.x with the SDK.

I'm happy to help with perfecting the Appwrite Client SDK, Feel free to drop a comment on this. Will move ahead with further plans

**Comment by AathifMahir** [comment]
Would love to see the Appwrite DotNet Client SDK getting on Par with other Client SDKs, Currently DotNet Maui, Uno Platform, Avalonia, etc.. getting lots of traction. DotNet devs would love to have option of using Appwrite as a backend for many different DotNet Applications
