### ISSUE TITLE
📚 Documentation: How to use the dotnet SDK?

### ISSUE THREAD

**Issue by Aronastu** [appwrite/sdk-for-dotnet#20]
### 💭 Description

for .NET there is missing documentation 
my question is how to filter ListDocuments() function 
database.ListDocuments(String collectionId,  list<object> ? filters = null, ...)

my question is how to filter any example pls , i dont know ```list<object> ? filters = null``` 

  but from my flutter and web experience, I was doing like this 
 queries: [
          Query.equal("uid", uid),
        ],
so how can Filer data inside ListDocuments() function in .NET, thanks. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I read the Code of Conduct

**Comment by joeyouss** [comment]
Hi
We currently do not have the .NET SDK released for Appwrite.

As and when it is released, we will include the documentation for it. Thanks

**Comment by eldadfux** [comment]
We've also added this quick start guide: https://appwrite.io/docs/quick-starts/dotnet

**Comment by eldadfux** [comment]
The new queries page on the docs also have .NET examples of how to call the different queries: https://appwrite.io/docs/products/databases/queries it should be very similar to what you're use to from Flutter.
